apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
type: Opaque
data:
  aws_access_key_id: "QUtJQTZFV0ZLRFZZRFdRM0tWQk8="
  aws_secret_access_key: "OE0wd3owN1JjMTBPZURUc2RBbmxLM3lwNlRLYkdIeGdwRnNoQjNXcQ=="