apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
        - name: backend-feed
          image: azeemahraji/udagram-api-feed:v2
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: aws-secrets
