apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: azeemahraji/udagram-frontend:v1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: aws-secrets
            - secretRef:
                name: postgres-secrets
